### PR TITLE
added test for deleting a node with a reference from a multiple property field

### PR DESCRIPTION
**Pull request by danrot**
This test is currently failing for jackalope-doctrine-dbal.

### CODE REVIEW

**Comment by dbu** [comment]
on which line does it fail? when removing the node, or on saving?

**Comment by danrot** [comment]
While saving. As far as I could research this issue is located in this line: https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Client.php#L919

The problem is that the id that should be deleted here is in target_id, not in source_id. But I didn't figure out how this could happen.

**Comment by dbu** [comment]
@lsmith77 any chance you could investigate on this one?

**Comment by lsmith77** [comment]
need a rebase .. I will try to look at it today .. but if I haven't done anything until tomorrow noon, I will not get to it until my return on Sunday evening next week

**Comment by lsmith77** [comment]
BTW when looking at this it might also make sense to look at https://github.com/jackalope/jackalope-doctrine-dbal/issues/287

**Comment by danrot** [comment]
@lsmith77 Rebased

**Comment by lsmith77** [comment]
this should fix the issue https://github.com/jackalope/jackalope-doctrine-dbal/pull/293

but its such a simple fix .. it makes me wonder if there isn't a bug ..

**Comment by lsmith77** [comment]
just noticed I have a local change but I am not sure why ..

```
diff --git a/tests/Writing/DeleteMethodsTest.php b/tests/Writing/DeleteMethodsTest.php
index 9deb827..e481c44 100644
--- a/tests/Writing/DeleteMethodsTest.php
+++ b/tests/Writing/DeleteMethodsTest.php
@@ -461,7 +461,7 @@ class DeleteMethodsTest extends \PHPCR\Test\BaseCase
 
         // 2) Get the referencing property and delete it
         $sourceprop = $this->node->getProperty('reference');
-        $sourceprop->setValue(array());
+        $sourceprop->setValue(null);
 
         // 4) Load the previously referenced node and remove it
         $destnode = $this->node->getNode('idExample');
```

**Comment by dbu** [comment]
that would not be the same. null deletes the property, array() would set a multivalue property to an empty list. multivalue can exist with 0 items in it.

**Comment by danrot** [comment]
@lsmith77 Probably this is the reason it's still not working for me :-)

**Comment by lsmith77** [comment]
this PR might need to be rebased

**Comment by danrot** [comment]
Why? GitHub can merge it, and also locally git tells me the branch is already up to date.

**Comment by lsmith77** [comment]
I want to ensure we do not introduce regressions in newly added tests since we develop changes for this test solely against this branch.

**Comment by lsmith77** [comment]
also we recently did some structural changes but if you already pulled them all is well.

**Comment by dbu** [comment]
i just checked this with jackalope-jackrabbit and had no failures. so once the doctrine-dbal issue is fixed this can be merged.

**Comment by dbu** [comment]
this test is fixed with https://github.com/jackalope/jackalope/commit/0c6bb8d0a9d5328a8e2eb2e295309acf7b05bc81 - which means it probably was a weird side effect of that problem.

**Comment by dbu** [comment]
merged in cc66a3d1ac9bbd0e1947580eb8af2a5170025775 - thanks a lot dan!

**Pull request closed without merging**
