### PR TITLE
Multivalue reference tests

### PR DESCRIPTION
**Pull request by dantleech**
Added multivalue reference test

### CODE REVIEW

**Comment by dantleech** [comment]
Updated.

**Comment by dbu** [comment]
hm, this broke even with https://github.com/jackalope/jackalope-doctrine-dbal/pull/231 - i reverted the merge. can you please have another look?

**Comment by dantleech** [comment]
ok .. so the other PR is ok and this test is broken?

**Comment by dbu** [comment]
i don't know. i assumed that both are fine, merged this and restarted the tests on the jackalope PR. then both jackalope dbal master and the PR had the same errors, so i am assuming the problem is with the changes in here. but could also be something went wrong and the tests are meant to fail without the fix, and the jackalope PR somehow does not correctly fix the problem.

**Pull request merged**
